apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mybar
  namespace: my-bar
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5m"
spec:
  rules:
    - host: "mybar.dvmalkin.ru"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: my-bar-service
                port:
                  number: 80
    - host: "debug.dvmalkin.ru"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: my-bar-service
                port:
                  number: 80
