apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mybar
spec:
  rules:
    - host: "mybar.dvmalkin.online"
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: my-bar-service
                port:
                  number: 8080
