version: "3.9"
services:
  postgres_bd:
    image: postgres:latest
    user: root
    volumes:
      - ./db-data:/var/postgres/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
