version: "3.9"
services:
  postgres_bd:
    image: postgres:latest
    user: root
    volumes:
      - ./db-data:/var/postgres/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  my-bar-end:
    image: danilmalkinnn/my_bar:0.0.5-SNAPSHOT
    user: root
    depends_on:
      - postgres_bd
    environment:
      DATABASE_HOST: postgres_bd
      DATABASE_PORT: "5432"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./backend-data:/var/backend/data
    ports:
      - "8080:8080"