server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, liveness, readiness, mappings, env

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: my-bar-app
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/api/login/oauth2/code/keycloak"
            provider: keycloak

        provider:
          keycloak:
            issuer-uri: ${KEY_CLOAK_URL:http://localhost:8081/realms/my-bar}
            user-name-attribute: preferred_username

  #      resourceserver:
  #        jwt:
  #          issuer-uri: ${KEY_CLOAK_URL:http://localhost:8081/realms/my-bar}
  #          jwk-set-uri: ${KEY_CLOAK_URL:http://localhost:8081/realms/my-bar}/protocol/openid-connect/token

  liquibase:
    enabled: true
    change-log: classpath:db/master.xml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml

  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin




logging:
  level:
    root: debug