server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
management:
  endpoint:
    health:
      probes.enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: health, prometheus, liveness, readiness, mappings

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
logging:
  level:
    root: debug