server:
  port: 8080
  servlet:
    context-path: /api
management:
  endpoint:
    health:
      probes.enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: health, prometheus, liveness, readiness, mappings

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${PG_URL:localhost:5432}/postgres
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}