{
 "title": "Spring Boot Caches",
 "description": "Spring Boot (Micrometer) with Caches.",
 "tags": [
  "prometheus",
  "spring-boot",
  "micrometer",
  "cache"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(cache_gets_total, namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(cache_gets_total{namespace=\"$namespace\"}, application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cache_gets_total{namespace=\"$namespace\", application=\"$application\"}, instance)"
    }
   },
   {
    "name": "cache_manager_name",
    "label": "Cache Manager",
    "query": {
     "query": "label_values(cache_gets_total{namespace=\"$namespace\",application=\"$application\", instance=~\"$instance\"}, cache_manager)"
    }
   },
   {
    "name": "cache_name",
    "label": "Cache",
    "query": {
     "query": "label_values(cache_gets_total{namespace=\"$namespace\",application=\"$application\", instance=~\"$instance\", cache_manager=~\"$cache_manager_name\"}, cache)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cache_size{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", cache_manager=~\"$cache_manager_name\", cache=~\"$cache_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Manager: $cache_manager_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "cache_manager_name"
  },
  {
   "title": "Gets: Hit",
   "type": "timeseries",
   "description": "The number of times cache lookup methods have returned a cached.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(cache_gets_total{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", cache_manager=~\"$cache_manager_name\", cache=~\"$cache_name\", result=\"hit\"}[$__rate_interval])) by (namespace, application, cache_manager, cache)",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Puts",
   "type": "timeseries",
   "description": "The number of entries added to the cache",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(cache_puts_total{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", cache_manager=~\"$cache_manager_name\", cache=~\"$cache_name\"}[$__rate_interval])) by (namespace, application, cache_manager, cache)",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Gets: Miss",
   "type": "timeseries",
   "description": "The number of times cache lookup methods have returned a uncached (newly loaded or null) value.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(cache_gets_total{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", cache_manager=~\"$cache_manager_name\", cache=~\"$cache_name\", result=\"miss\"}[$__rate_interval])) by (namespace, application, cache_manager, cache)",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "timeseries",
   "description": "The number of times the cache was evicted.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(cache_evictions_total{namespace=\"$namespace\", application=\"$application\", instance=~\"$instance\", cache_manager=~\"$cache_manager_name\", cache=~\"$cache_name\"}[$__rate_interval])) by (namespace, application, cache_manager, cache)",
     "legendFormat": "{{cache}}"
    }
   ]
  }
 ]
}