---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mybar-backend-file-storage-pv
  namespace: my-bar
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/mybar-data/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-bar
  namespace: my-bar
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Укажите требуемый размер объема
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-bar-project
  namespace: my-bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-bar-project
  template:
    metadata:
      labels:
        app: my-bar-project
    spec:
      containers:
        - name: my-bar-project
          image: ${IMAGE_NAME}
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: postgres-service
            - name: DATABASE_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: my-bar-service
  namespace: my-bar
spec:
  selector:
    app: my-bar-project
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: my-bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.2
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---


apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: my-bar
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: Secret
metadata:
  namespace: my-bar
  name: postgres-secret
type: Opaque
data:
  password: cG9zdGdyZXM=
# Используйте команду `echo -n 'yourpassword' | base64` для создания этого значения
#  password: postgres
