apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-bar-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-bar-project
  template:
    metadata:
      labels:
        app: my-bar-project
    spec:
      containers:
        - name: my-bar-project
          image: ${IMAGE_NAME}
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: postgres-service
            - name: DATABASE_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: my-bar-service
spec:
  selector:
    app: my-bar-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.2
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
#  password: ${PG_PASS_BASE64} # Используйте команду `echo -n 'yourpassword' | base64` для создания этого значения
  password: postgres
