---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mybar-backend-file-storage-pv
  namespace: my-bar
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/mybar-data/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-bar
  namespace: my-bar
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Укажите требуемый размер объема
---