name: CI Pipeline

on:
  push:
    branches:
      - develop  # Триггер на пуш в ветку dev
  pull_request:
    branches:
      - '*'  # Триггер на создание MR в любую ветку

jobs:
  build-on-merge-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Maven build
        run: mvn package


