name: CI Pipeline

on:
  push:
    branches:
      - '*' # Триггер на пуш в ветку dev
  pull_request:
    branches:
      - '*'  # Триггер на создание MR в любую ветку

jobs:
  build-on-merge-request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Условие для запуска работы
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'liberica'

      - name: Maven build
        run: mvn --batch-mode --update-snapshots package


