name: CI/CD Pipeline

on:
  workflow_dispatch:
    branches: '*'

  push:
    branches:
      - master
env:
  IMAGE: danilmalkinnn/my_bar
  VERSION: latest

jobs:
  Push_in_DockerHub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'liberica'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: 21
          maven-version: 3.8.1

      - name: Set repository name
        run: echo "IMAGE=danilmalkinnn/my_bar" >> $GITHUB_ENV
      - name: Set Version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t ${{env.IMAGE}}:${{ env.VERSION }} .

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: show images
        run: docker image ls
      - name: Push Docker Image
        run: docker push ${{env.IMAGE}}:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: Push_in_DockerHub
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'liberica'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Set Version
        run: echo "VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - name: Replace environment variables
        uses: nowactions/envsubst@v1
        with:
          input: k8s/config.yaml
          output: k8s/ready/deployment.yaml
        env:
          IMAGE_NAME: ${{env.IMAGE}}:${{ env.VERSION }}

      - name: Setup kubectl client
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0

      - name: Set Kubernetes context
        uses: Azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Deploy to the Kubernetes cluster
        uses: Azure/k8s-deploy@v4
        with:
          manifests: k8s/ready/

